"""One-page molecular report: identity, drug-likeness, and a summary.

Combines the interpretation layer into a shareable artifact in Markdown, HTML
(with a 2D structure depiction), or JSON. Descriptive only, like the rest of
the open tool: no ADMET, pKa, solubility, or binding prediction.
"""

from __future__ import annotations

import json
from typing import Any, Dict

from .__about__ import __version__
from .exceptions import InvalidSMILESError, RDKitNotAvailableError
from .interpret import calculate_druglikeness, summarize

try:
    from rdkit import Chem
    from rdkit.Chem import rdMolDescriptors
    from rdkit.Chem.Draw import rdMolDraw2D

    RDKIT_AVAILABLE = True
except ImportError:  # pragma: no cover - exercised only without RDKit
    RDKIT_AVAILABLE = False

# (label, druglikeness key)
_ROWS = [
    ("Molecular weight", "molecular_weight"),
    ("logP", "logp"),
    ("TPSA", "tpsa"),
    ("H-bond donors", "h_bond_donors"),
    ("H-bond acceptors", "h_bond_acceptors"),
    ("Rotatable bonds", "rotatable_bonds"),
    ("Aromatic rings", "aromatic_rings"),
    ("Fraction sp3", "fraction_csp3"),
    ("QED", "qed"),
]

_FOOTER = (
    "Generated by NovoMD {version}. Descriptive cheminformatics only: "
    "logP, TPSA, QED, Lipinski, Veber. Not ADMET, pKa, solubility, or binding."
)


def _depiction_svg(mol: Any, width: int = 360, height: int = 260) -> str:
    drawer = rdMolDraw2D.MolDraw2DSVG(width, height)
    drawer.DrawMolecule(mol)
    drawer.FinishDrawing()
    return str(drawer.GetDrawingText())


def _rule_line(druglikeness: Dict[str, Any]) -> tuple[str, str]:
    lip = druglikeness["lipinski"]["violations"]
    veber = druglikeness["veber"]["violations"]
    lip_text = "no violations" if not lip else ", ".join(lip)
    veber_text = "passes" if not veber else ", ".join(veber)
    return lip_text, veber_text


def _markdown(smiles: str, formula: str, d: Dict[str, Any]) -> str:
    lip_text, veber_text = _rule_line(d)
    lines = [
        f"# Molecular report: {formula}",
        "",
        f"`{smiles}`",
        "",
        "| Property | Value |",
        "| --- | --- |",
    ]
    lines += [f"| {label} | {d[key]} |" for label, key in _ROWS]
    lines += [
        "",
        f"**Lipinski:** {lip_text}  ",
        f"**Veber:** {veber_text}",
        "",
        f"> {summarize(d)}",
        "",
        f"_{_FOOTER.format(version=__version__)}_",
        "",
    ]
    return "\n".join(lines)


def _html(smiles: str, formula: str, d: Dict[str, Any], svg: str) -> str:
    lip_text, veber_text = _rule_line(d)
    rows = "\n".join(f"      <tr><td>{label}</td><td>{d[key]}</td></tr>" for label, key in _ROWS)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>NovoMD report: {formula}</title>
<style>
  body {{ font-family: -apple-system, Helvetica, Arial, sans-serif;
         background: #F8F6F3; color: #2D2A26; margin: 0; padding: 2rem; }}
  .card {{ max-width: 640px; margin: 0 auto; background: #fff;
          border: 1px solid #E4DED6; padding: 1.5rem 2rem; }}
  h1 {{ font-weight: 600; margin: 0 0 .25rem; }}
  code {{ color: #6B645C; }}
  .accent {{ color: #B8704B; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  td {{ padding: .35rem .5rem; border-bottom: 1px solid #EFEAE3; }}
  td:last-child {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .rules {{ margin: .5rem 0; }}
  blockquote {{ border-left: 3px solid #B8704B; margin: 1rem 0;
               padding: .25rem 0 .25rem 1rem; color: #2D2A26; }}
  footer {{ color: #6B645C; font-size: .8rem; margin-top: 1.5rem; }}
  svg {{ max-width: 100%; height: auto; }}
</style>
</head>
<body>
  <div class="card">
    <h1 class="accent">{formula}</h1>
    <code>{smiles}</code>
    <div>{svg}</div>
    <table>
{rows}
    </table>
    <div class="rules"><strong>Lipinski:</strong> {lip_text} &middot;
      <strong>Veber:</strong> {veber_text}</div>
    <blockquote>{summarize(d)}</blockquote>
    <footer>{_FOOTER.format(version=__version__)}</footer>
  </div>
</body>
</html>
"""


def generate_report(smiles: str, fmt: str = "markdown") -> str:
    """Build a one-page molecular report.

    Args:
        smiles: The molecule as a SMILES string.
        fmt: ``"markdown"`` (default), ``"html"`` (with a 2D depiction), or ``"json"``.

    Raises:
        RDKitNotAvailableError: RDKit is not installed.
        InvalidSMILESError: The SMILES string could not be parsed.
        ValueError: ``fmt`` is not one of the supported formats.
    """
    if not RDKIT_AVAILABLE:
        raise RDKitNotAvailableError(
            "RDKit is required for this operation but is not installed. "
            "Install it with: pip install novomd"
        )

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise InvalidSMILESError(f"Invalid SMILES string: {smiles!r}")

    formula = rdMolDescriptors.CalcMolFormula(mol)
    d = calculate_druglikeness(smiles)

    if fmt == "json":
        return json.dumps({**d, "formula": formula, "summary": summarize(d)}, indent=2)
    if fmt == "markdown":
        return _markdown(smiles, formula, d)
    if fmt == "html":
        return _html(smiles, formula, d, _depiction_svg(mol))

    raise ValueError(f"Unknown report format: {fmt!r} (use markdown, html, or json)")
